---
- name: first playbook
  hosts: all
  become: true
  tasks:

  - name: install packages for Ubuntu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install packages for Fedora
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
