---
- name: Install apache on web servers
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"
- name: Ensure Apache is running
  tags: ubuntu,apache
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"
- name: Copy HTML file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"
- name: Change email address for admin
  tags: ubuntu,apache
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ^ServerAdmin
    line: ServerAdmin admin@server.com
    when: ansible_distribution == "Ubuntu"
    register: httpd
